/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ApiAiBackendsRouteImport } from './routes/api/ai/backends'
import { Route as ApiAiStreamRouteImport } from './routes/api/ai/stream'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiBackendsRoute = ApiAiBackendsRouteImport.update({
  id: '/api/ai/backends',
  path: '/api/ai/backends',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiStreamRoute = ApiAiStreamRouteImport.update({
  id: '/api/ai/stream',
  path: '/api/ai/stream',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/api/ai/backends': typeof ApiAiBackendsRoute
  '/api/ai/stream': typeof ApiAiStreamRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/api/ai/backends': typeof ApiAiBackendsRoute
  '/api/ai/stream': typeof ApiAiStreamRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/api/ai/backends': typeof ApiAiBackendsRoute
  '/api/ai/stream': typeof ApiAiStreamRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/login' | '/api/ai/backends' | '/api/ai/stream' | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/login' | '/api/ai/backends' | '/api/ai/stream' | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/api/ai/backends'
    | '/api/ai/stream'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  ApiAiBackendsRoute: typeof ApiAiBackendsRoute
  ApiAiStreamRoute: typeof ApiAiStreamRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai/backends': {
      id: '/api/ai/backends'
      path: '/api/ai/backends'
      fullPath: '/api/ai/backends'
      preLoaderRoute: typeof ApiAiBackendsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai/stream': {
      id: '/api/ai/stream'
      path: '/api/ai/stream'
      fullPath: '/api/ai/stream'
      preLoaderRoute: typeof ApiAiStreamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  ApiAiBackendsRoute: ApiAiBackendsRoute,
  ApiAiStreamRoute: ApiAiStreamRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
